export const ADD_CARD_TO_GAME_DECK = 'ADD_CARD_TO_GAME_DECK'
export const SET_INITIAL_PLAYER_STATE = 'SET_INITIAL_PLAYER_STATE'
export const SET_SELECTED_CARD = 'SET_SELECTED_CARD'
export const UN_SET_SELECTED_CARD = 'UN_SET_SELECTED_CARD'
